plugins {
    id "com.android.application"
}

android {
    namespace "com.masterpiece.wallpapers.ai"
    compileSdk 36

    buildFeatures { buildConfig true }

    defaultConfig {
        applicationId "com.masterpiece.wallpapers.ai1"
        minSdk 23
        targetSdk 36
        versionCode 8
        versionName "1.7"
    }
}

dependencies {
    implementation "androidx.appcompat:appcompat:1.7.1"
    implementation "com.google.android.material:material:1.12.0"
    implementation "com.google.android.gms:play-services-ads:24.5.0"
    implementation "com.android.billingclient:billing:8.0.0"
}
